"""Pydantic schemas for the fraud module."""
import enum
import uuid
from datetime import datetime
from decimal import Decimal
from typing import Literal

from pydantic import BaseModel, Field

from app.fraud.models import FraudCaseStatus, FraudFlagCode


class FraudFlagPublic(BaseModel):
    id: uuid.UUID
    code: FraudFlagCode
    points: Decimal
    description: str


class FraudCaseSummary(BaseModel):
    id: uuid.UUID
    transaction_id: uuid.UUID
    user_id: uuid.UUID
    risk_score: Decimal
    status: FraudCaseStatus
    hold_amount: Decimal
    hold_currency: str
    created_at: datetime
    flag_codes: list[FraudFlagCode]


class FraudRiskLevel(str, enum.Enum):
    """The Fraud Investigation Agent's qualitative read on a case — a
    separate concept from FraudFlagCode (which flags fired) and from
    risk_score (the deterministic point total). Advisory only: never
    written by anything except ai/fraud/agent.py, never read by
    fraud/service.py's scoring logic."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class FraudAgentAnalysisPublic(BaseModel):
    """The Fraud Investigation Agent's cached output for one case —
    JSON-serialized into FraudCase.agent_analysis (see that column's
    comment in fraud/models.py) and parsed back out by
    FraudService.to_detail(). Advisory only; risk_score above is the
    authoritative, unmodified deterministic score."""

    risk_level: FraudRiskLevel
    explanation: str
    generated_at: datetime
    summary: str | None = None
    case_overview: dict = Field(default_factory=dict)
    behavioral_analysis: dict = Field(default_factory=dict)
    velocity_analysis: dict = Field(default_factory=dict)
    merchant_analysis: dict = Field(default_factory=dict)
    device_analysis: dict = Field(default_factory=dict)
    historical_context: dict = Field(default_factory=dict)
    suspicious_signals: list[str] = Field(default_factory=list)
    reassuring_signals: list[str] = Field(default_factory=list)
    data_gaps: list[str] = Field(default_factory=list)
    recommended_checks: list[str] = Field(default_factory=list)


class FrozenCardPublic(BaseModel):
    """The card FraudService.get_frozen_card_for_case() found linked to this
    case, present only while it's still frozen with freeze_reason ==
    FRAUD_HOLD. Drives the admin panel's "Activate card" button — absent
    once the card has been reactivated (or if the transaction under review
    wasn't a card payment at all)."""

    id: uuid.UUID
    last_four: str
    masked_pan: str
    frozen_at: datetime | None


class FraudCaseDetail(FraudCaseSummary):
    decided_by_admin_id: uuid.UUID | None
    decided_at: datetime | None
    flags: list[FraudFlagPublic]
    transaction_amount: Decimal
    transaction_currency: str
    transaction_description: str | None
    transaction_created_at: datetime
    agent_analysis: FraudAgentAnalysisPublic | None = None
    frozen_card: FrozenCardPublic | None = None
    # Fixed, non-LLM safety reminder — set deterministically by
    # FraudService.to_detail() whenever frozen_card is present, never
    # generated by ai/fraud/agent.py. Kept as a sibling of agent_analysis
    # (not inside it) so it's shown as soon as the case loads, not gated
    # behind an admin first running the AI investigation.
    card_hold_notice: str | None = None


class FraudDecisionRequest(BaseModel):
    action: Literal["APPROVE", "REJECT"]
