"""FX quotes (architecture.md §43 Migration 2), plus corrective ALTERs for
drift between 0001's hand-written DDL and the actual models: several
timestamp columns were left nullable and users.email/phone had a redundant
unique constraint + separate non-unique index instead of one unique index.
Autogenerated against the running dev database, then hand-cleaned.

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-18
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "fx_quotes",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("source_currency", sa.String(3), nullable=False),
        sa.Column("target_currency", sa.String(3), nullable=False),
        sa.Column("source_amount", sa.Numeric(18, 2), nullable=False),
        sa.Column("target_amount", sa.Numeric(18, 2), nullable=False),
        sa.Column("exchange_rate", sa.Numeric(18, 8), nullable=False),
        sa.Column("fee", sa.Numeric(18, 2), nullable=False),
        sa.Column(
            "status", sa.Enum("CREATED", "ACCEPTED", "EXPIRED", name="fx_quote_status"), nullable=False,
            server_default="CREATED",
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    for table, column in [
        ("transactions", "created_at"),
        ("user_devices", "first_seen_at"),
        ("user_devices", "last_seen_at"),
        ("user_sessions", "created_at"),
        ("user_sessions", "last_activity_at"),
        ("users", "created_at"),
        ("users", "updated_at"),
        ("wallet_ledger_entries", "created_at"),
        ("wallets", "created_at"),
        ("wallets", "updated_at"),
    ]:
        op.alter_column(table, column, existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)

    op.drop_constraint("users_email_key", "users", type_="unique")
    op.drop_constraint("users_phone_key", "users", type_="unique")
    op.drop_index("ix_users_email", table_name="users")
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.drop_index("ix_users_phone", table_name="users")
    op.create_index("ix_users_phone", "users", ["phone"], unique=True)


def downgrade() -> None:
    op.drop_index("ix_users_phone", table_name="users")
    op.create_index("ix_users_phone", "users", ["phone"], unique=False)
    op.drop_index("ix_users_email", table_name="users")
    op.create_index("ix_users_email", "users", ["email"], unique=False)
    op.create_unique_constraint("users_phone_key", "users", ["phone"])
    op.create_unique_constraint("users_email_key", "users", ["email"])

    for table, column in [
        ("transactions", "created_at"),
        ("user_devices", "first_seen_at"),
        ("user_devices", "last_seen_at"),
        ("user_sessions", "created_at"),
        ("user_sessions", "last_activity_at"),
        ("users", "created_at"),
        ("users", "updated_at"),
        ("wallet_ledger_entries", "created_at"),
        ("wallets", "created_at"),
        ("wallets", "updated_at"),
    ]:
        op.alter_column(table, column, existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)

    op.drop_table("fx_quotes")
    sa.Enum(name="fx_quote_status").drop(op.get_bind(), checkfirst=True)
